### ISSUE TITLE
Add footer bar

### ISSUE THREAD

**Issue by Monjola** [DM2518-mobut20/dothemath-app-frontend#2]
Add the footer bar that is always at the bottom of the page even when scrolling. should contain 4 buttons, chat, calculator, formula sheet and profile.

**Comment by iRobsc** [comment]
![image](https://user-images.githubusercontent.com/5315633/80470168-e79e1d00-8941-11ea-85ca-879aa4617320.png)

**Comment by Monjola** [comment]
![image](https://user-images.githubusercontent.com/22137237/80642739-4315fb00-8a67-11ea-9298-61698a361747.png)
Footer bar is there visually. Buttons don't do anything yet.

**Comment by Monjola** [comment]
footer bar (Tabbar.tsx) now routes to Profile.tsx, Calculator.tsx, App.tsx and Formulasheet.tsx
